//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ort.edu.uy.obligatorio2.ClientWebServiceLogic.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeviceInfoWrapper", Namespace="http://schemas.datacontract.org/2004/07/uy.edu.ort.obligatorio.Commons")]
    [System.SerializableAttribute()]
    public partial class DeviceInfoWrapper : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ort.edu.uy.obligatorio2.ClientWebServiceLogic.ServiceReference1.DeviceInfo[] ListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((this.ErrorField.Equals(value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ort.edu.uy.obligatorio2.ClientWebServiceLogic.ServiceReference1.DeviceInfo[] List {
            get {
                return this.ListField;
            }
            set {
                if ((object.ReferenceEquals(this.ListField, value) != true)) {
                    this.ListField = value;
                    this.RaisePropertyChanged("List");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeviceInfo", Namespace="http://schemas.datacontract.org/2004/07/uy.edu.ort.obligatorio.Commons")]
    [System.SerializableAttribute()]
    public partial class DeviceInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeviceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ort.edu.uy.obligatorio2.ClientWebServiceLogic.ServiceReference1.DeviceFailureInfo LastFailureInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ort.edu.uy.obligatorio2.ClientWebServiceLogic.ServiceReference1.DeviceStatusInfo LastStatusInfoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeviceId {
            get {
                return this.DeviceIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DeviceIdField, value) != true)) {
                    this.DeviceIdField = value;
                    this.RaisePropertyChanged("DeviceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ort.edu.uy.obligatorio2.ClientWebServiceLogic.ServiceReference1.DeviceFailureInfo LastFailureInfo {
            get {
                return this.LastFailureInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.LastFailureInfoField, value) != true)) {
                    this.LastFailureInfoField = value;
                    this.RaisePropertyChanged("LastFailureInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ort.edu.uy.obligatorio2.ClientWebServiceLogic.ServiceReference1.DeviceStatusInfo LastStatusInfo {
            get {
                return this.LastStatusInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.LastStatusInfoField, value) != true)) {
                    this.LastStatusInfoField = value;
                    this.RaisePropertyChanged("LastStatusInfo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeviceFailureInfo", Namespace="http://schemas.datacontract.org/2004/07/uy.edu.ort.obligatorio.Commons")]
    [System.SerializableAttribute()]
    public partial class DeviceFailureInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime AlarmDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AlarmLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AlarmTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime AlarmDateTime {
            get {
                return this.AlarmDateTimeField;
            }
            set {
                if ((this.AlarmDateTimeField.Equals(value) != true)) {
                    this.AlarmDateTimeField = value;
                    this.RaisePropertyChanged("AlarmDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AlarmLevel {
            get {
                return this.AlarmLevelField;
            }
            set {
                if ((this.AlarmLevelField.Equals(value) != true)) {
                    this.AlarmLevelField = value;
                    this.RaisePropertyChanged("AlarmLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AlarmType {
            get {
                return this.AlarmTypeField;
            }
            set {
                if ((this.AlarmTypeField.Equals(value) != true)) {
                    this.AlarmTypeField = value;
                    this.RaisePropertyChanged("AlarmType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeviceStatusInfo", Namespace="http://schemas.datacontract.org/2004/07/uy.edu.ort.obligatorio.Commons")]
    [System.SerializableAttribute()]
    public partial class DeviceStatusInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeviceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool StatusOnOffField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long UpTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeviceId {
            get {
                return this.DeviceIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DeviceIdField, value) != true)) {
                    this.DeviceIdField = value;
                    this.RaisePropertyChanged("DeviceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool StatusOnOff {
            get {
                return this.StatusOnOffField;
            }
            set {
                if ((this.StatusOnOffField.Equals(value) != true)) {
                    this.StatusOnOffField = value;
                    this.RaisePropertyChanged("StatusOnOff");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long UpTime {
            get {
                return this.UpTimeField;
            }
            set {
                if ((this.UpTimeField.Equals(value) != true)) {
                    this.UpTimeField = value;
                    this.RaisePropertyChanged("UpTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeviceFailureInfoWrapper", Namespace="http://schemas.datacontract.org/2004/07/uy.edu.ort.obligatorio.Commons")]
    [System.SerializableAttribute()]
    public partial class DeviceFailureInfoWrapper : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ort.edu.uy.obligatorio2.ClientWebServiceLogic.ServiceReference1.DeviceFailureInfo[] ListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((this.ErrorField.Equals(value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ort.edu.uy.obligatorio2.ClientWebServiceLogic.ServiceReference1.DeviceFailureInfo[] List {
            get {
                return this.ListField;
            }
            set {
                if ((object.ReferenceEquals(this.ListField, value) != true)) {
                    this.ListField = value;
                    this.RaisePropertyChanged("List");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeviceStatusInfoWrapper", Namespace="http://schemas.datacontract.org/2004/07/uy.edu.ort.obligatorio.Commons")]
    [System.SerializableAttribute()]
    public partial class DeviceStatusInfoWrapper : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ort.edu.uy.obligatorio2.ClientWebServiceLogic.ServiceReference1.DeviceStatusInfo[] ListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((this.ErrorField.Equals(value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ort.edu.uy.obligatorio2.ClientWebServiceLogic.ServiceReference1.DeviceStatusInfo[] List {
            get {
                return this.ListField;
            }
            set {
                if ((object.ReferenceEquals(this.ListField, value) != true)) {
                    this.ListField = value;
                    this.RaisePropertyChanged("List");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IClientDevicesService")]
    public interface IClientDevicesService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientDevicesService/Echo", ReplyAction="http://tempuri.org/IClientDevicesService/EchoResponse")]
        string Echo(string text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientDevicesService/GetDevicesForClient", ReplyAction="http://tempuri.org/IClientDevicesService/GetDevicesForClientResponse")]
        ort.edu.uy.obligatorio2.ClientWebServiceLogic.ServiceReference1.DeviceInfoWrapper GetDevicesForClient(string idClient);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientDevicesService/GetDeviceFaults", ReplyAction="http://tempuri.org/IClientDevicesService/GetDeviceFaultsResponse")]
        ort.edu.uy.obligatorio2.ClientWebServiceLogic.ServiceReference1.DeviceFailureInfoWrapper GetDeviceFaults(string idDevice, int resultMaxSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientDevicesService/GetDeviceStatuses", ReplyAction="http://tempuri.org/IClientDevicesService/GetDeviceStatusesResponse")]
        ort.edu.uy.obligatorio2.ClientWebServiceLogic.ServiceReference1.DeviceStatusInfoWrapper GetDeviceStatuses(string idDevice, int resultMaxSize);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClientDevicesServiceChannel : ort.edu.uy.obligatorio2.ClientWebServiceLogic.ServiceReference1.IClientDevicesService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClientDevicesServiceClient : System.ServiceModel.ClientBase<ort.edu.uy.obligatorio2.ClientWebServiceLogic.ServiceReference1.IClientDevicesService>, ort.edu.uy.obligatorio2.ClientWebServiceLogic.ServiceReference1.IClientDevicesService {
        
        public ClientDevicesServiceClient() {
        }
        
        public ClientDevicesServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClientDevicesServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientDevicesServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientDevicesServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Echo(string text) {
            return base.Channel.Echo(text);
        }
        
        public ort.edu.uy.obligatorio2.ClientWebServiceLogic.ServiceReference1.DeviceInfoWrapper GetDevicesForClient(string idClient) {
            return base.Channel.GetDevicesForClient(idClient);
        }
        
        public ort.edu.uy.obligatorio2.ClientWebServiceLogic.ServiceReference1.DeviceFailureInfoWrapper GetDeviceFaults(string idDevice, int resultMaxSize) {
            return base.Channel.GetDeviceFaults(idDevice, resultMaxSize);
        }
        
        public ort.edu.uy.obligatorio2.ClientWebServiceLogic.ServiceReference1.DeviceStatusInfoWrapper GetDeviceStatuses(string idDevice, int resultMaxSize) {
            return base.Channel.GetDeviceStatuses(idDevice, resultMaxSize);
        }
    }
}
